# Lista de marcadores discursivos, fontes: 
# https://escritacientifica.sc.usp.br/scipo/consulta_marcadores_popup.php?componente=resumo
# https://leresonhar.wordpress.com/wp-content/uploads/2017/04/conetores-discursivos1.pdf
marcadores_discursivos = [
    "é o que se passa com",
    "a não ser que",
    "antes de mais nada",
    "com a intenção de",
    "com o fim de",
    "com o objetivo de",
    "com o propósito de",
    "como se pode ver",
    "de tal forma que",
    "dito de outro modo",
    "estou em crer que",
    "isto não significa que",
    "é o caso de",
    "a fim de",
    "a menos que",
    "a meu ver",
    "acima de tudo",
    "antes de tudo",
    "ao invés de",
    "ao passo que",
    "ao tempo que",
    "com o fito de",
    "da mesma forma",
    "da mesma maneira",
    "de acordo com",
    "de conformidade com",
    "de forma a",
    "de forma idêntica",
    "de forma similar",
    "de igual forma",
    "de igual maneira",
    "de igual modo",
    "de jeito nenhum",
    "de maneira oposta",
    "de modo algum",
    "de modo oposto",
    "de modo que",
    "de outro lado",
    "de qualquer forma",
    "de um lado",
    "dias mais tarde",
    "do mesmo modo",
    "em hipótese alguma",
    "em meu entender",
    "em outras palavras",
    "em primeiro lugar",
    "em que pese",
    "em segundo lugar",
    "em vez de",
    "em último lugar",
    "isto significa que",
    "na minha opinião",
    "num primeiro momento",
    "pela mesma razão",
    "por causa de",
    "por esta razão",
    "por mais que",
    "por outras palavras",
    "por outro lado",
    "por tudo isso",
    "por um lado",
    "quer isto dizer",
    "se bem que",
    "sem dúvida que",
    "só para exemplificar",
    "só para ilustrar",
    "todas as vezes",
    "uma vez que",
    "à medida que",
    "à proporção que",
    "é evidente que",
    "é possível que",
    "é óbvio que",
    "a posteriori",
    "a priori",
    "a saber",
    "agora já",
    "ainda assim",
    "ainda que",
    "além de",
    "além disso",
    "anos após",
    "antes de",
    "antes que",
    "ao contrário",
    "apesar de",
    "apesar disso",
    "aqui está",
    "assim como",
    "assim que",
    "atente-se em",
    "até mesmo",
    "até que",
    "bem como",
    "com certeza",
    "com efeito",
    "com exatidão",
    "com intuito",
    "como ainda",
    "como consequência",
    "como vimos",
    "contanto que",
    "dado que",
    "daí que",
    "de certo",
    "de facto",
    "de fato",
    "de novo",
    "de repente",
    "de seguida",
    "de súbito",
    "de verdade",
    "depois de",
    "depois que",
    "desde quando",
    "desde que",
    "dessa forma",
    "dessa maneira",
    "desse modo",
    "desta forma",
    "desta maneira",
    "deste modo",
    "doutro modo",
    "e ainda",
    "em alternativa",
    "em baixo",
    "em cima",
    "em conclusão",
    "em consequência",
    "em particular",
    "em princípio",
    "em resumo",
    "em suma",
    "em síntese",
    "entre outros",
    "exceto se",
    "isto é",
    "já que",
    "logo após",
    "logo que",
    "mais corretamente",
    "mais precisamente",
    "mas também",
    "meses depois",
    "mesmo assim",
    "mesmo que",
    "na verdade",
    "naquele sítio",
    "naturalmente que",
    "nesse caso",
    "nesse contexto",
    "neste caso",
    "neste contexto",
    "no entanto",
    "no meio",
    "note-se que",
    "noutras palavras",
    "noutros termos",
    "numa palavra",
    "não apenas",
    "não obstante",
    "não somente",
    "não só",
    "ou então",
    "ou melhor",
    "ou seja",
    "para começar",
    "para que",
    "para terminar",
    "parece-me que",
    "pelo contrário",
    "pelo que",
    "pois que",
    "por analogia",
    "por certo",
    "por conseguinte",
    "por exemplo",
    "por isso",
    "por oposição",
    "por ventura",
    "por último",
    "posto que",
    "quanto mais",
    "quer dizer",
    "salvo que",
    "sem dúvida",
    "sempre que",
    "senão quando",
    "só se",
    "tais como",
    "tal como",
    "tanto mais",
    "visto que",
    "à direita",
    "à esquerda",
    "à frente",
    "é provávelque",
    " que",
    "acaso",
    "ainda",
    "aliás",
    "analogamente",
    "antes",
    "apenas",
    "após",
    "assim",
    "atrás",
    "até",
    "caso",
    "certamente",
    "começando",
    "como",
    "concluindo",
    "conclusivamente",
    "conforme",
    "consequentemente",
    "consoante",
    "constate-se",
    "contrariamente",
    "contudo",
    "daí",
    "decerto",
    "depois",
    "desde",
    "e",
    "efetivamente",
    "eis",
    "embora",
    "emseguida",
    "enfim",
    "enquanto",
    "entretanto",
    "então",
    "especificamente",
    "essencialmente",
    "evidentemente",
    "exatamente",
    "exato",
    "exclusive",
    "factualmente",
    "finalizando",
    "finalmente",
    "fora",
    "igualmente",
    "imprevistamente",
    "inclusive",
    "indubitavelmente",
    "inegavelmente",
    "inesperadamente",
    "inquestionavelmente",
    "jamais",
    "logo",
    "mal",
    "malgrado",
    "mas",
    "menos",
    "mesmo",
    "nada",
    "nem",
    "ninguém",
    "nomeadamente",
    "novamente",
    "nunca",
    "não",
    "obviamente",
    "opostamente",
    "oposto",
    "ora",
    "ou",
    "para",
    "paraterminar",
    "pois",
    "porquanto",
    "porque",
    "portanto",
    "porém",
    "possivelmente",
    "primeira",
    "primeiramente",
    "primeiro",
    "primordialmente",
    "principalmente",
    "provavelmente",
    "quando",
    "quanto",
    "que",
    "quer",
    "realmente",
    "recapitulando",
    "repare-se",
    "resumidamente",
    "salvo",
    "se",
    "segunda",
    "segundo",
    "semelhantemente",
    "senão",
    "sequer",
    "similarmente",
    "sintetizando",
    "sob",
    "sobre",
    "sobretudo",
    "somente",
    "subitamente",
    "surpreendentemente",
    "só",
    "tal",
    "talvez",
    "tamanho",
    "também",
    "tampouco",
    "tanto",
    "tirante",
    "todavia",
    "tão",
    "ultimamente",
    "vede",
    "veja-se",
    "verdade",
    "verdadeiramente",
    "verdadeiro",
    "óbvio"
]

titulo_1_constituicao_88 = """
Art. 1º A República Federativa do Brasil, formada pela união indissolúvel dos Estados e Municípios e do Distrito Federal, constitui-se em Estado Democrático de Direito e tem como fundamentos:

I - a soberania;

II - a cidadania

III - a dignidade da pessoa humana;

IV - os valores sociais do trabalho e da livre iniciativa;            (Vide Lei nº 13.874, de 2019)

V - o pluralismo político.

Parágrafo único. Todo o poder emana do povo, que o exerce por meio de representantes eleitos ou diretamente, nos termos desta Constituição.

 Art. 2º São Poderes da União, independentes e harmônicos entre si, o Legislativo, o Executivo e o Judiciário.

 Art. 3º Constituem objetivos fundamentais da República Federativa do Brasil:

I - construir uma sociedade livre, justa e solidária;

II - garantir o desenvolvimento nacional;

III - erradicar a pobreza e a marginalização e reduzir as desigualdades sociais e regionais;

IV - promover o bem de todos, sem preconceitos de origem, raça, sexo, cor, idade e quaisquer outras formas de discriminação.

 Art. 4º A República Federativa do Brasil rege-se nas suas relações internacionais pelos seguintes princípios:

I - independência nacional;

II - prevalência dos direitos humanos;

III - autodeterminação dos povos;

IV - não-intervenção;

V - igualdade entre os Estados;

VI - defesa da paz;

VII - solução pacífica dos conflitos;

VIII - repúdio ao terrorismo e ao racismo;

IX - cooperação entre os povos para o progresso da humanidade;

X - concessão de asilo político.

Parágrafo único. A República Federativa do Brasil buscará a integração econômica, política, social e cultural dos povos da América Latina, visando à formação de uma comunidade latino-americana de nações.
"""

declaracao_direitos_humanos = """
Todos os seres humanos nascem livres e iguais em dignidade e direitos. São dotados de razão e consciência e devem agir em relação uns aos outros com espírito de fraternidade.
Todo ser humano tem capacidade para gozar os direitos e as liberdades estabelecidos nesta Declaração, sem distinção de qualquer espécie, seja de raça, cor, sexo, língua, religião, opinião política ou de outra natureza, origem nacional ou social, riqueza, nascimento, ou qualquer outra condição. 
Não será também feita nenhuma distinção fundada na condição política, jurídica ou internacional do país ou território a que pertença uma pessoa, quer se trate de um território independente, sob tutela, sem governo próprio, quer sujeito a qualquer outra limitação de soberania.
Todo ser humano tem direito à vida, à liberdade e à segurança pessoal.
Ninguém será mantido em escravidão ou servidão; a escravidão e o tráfico de escravos serão proibidos em todas as suas formas.
Ninguém será submetido à tortura, nem a tratamento ou castigo cruel, desumano ou degradante.
Todo ser humano tem o direito de ser, em todos os lugares, reconhecido como pessoa perante a lei.
Todos são iguais perante a lei e têm direito, sem qualquer distinção, a igual proteção da lei. Todos têm direito a igual proteção contra qualquer discriminação que viole a presente Declaração e contra qualquer incitamento a tal discriminação.
Todo ser humano tem direito a receber dos tribunais nacionais competentes remédio efetivo para os atos que violem os direitos fundamentais que lhe sejam reconhecidos pela constituição ou pela lei.
Ninguém será arbitrariamente preso, detido ou exilado.
Todo ser humano tem direito, em plena igualdade, a uma justa e pública audiência por parte de um tribunal independente e imparcial, para decidir seus direitos e deveres ou fundamento de qualquer acusação criminal contra ele.
"""